#!/usr/bin/env python3
"""WG-006 task tracking.

Keeps the generated **Task index** in docs/IMPLEMENTATION_STATUS.md in sync with
the task list in docs/BACKLOG.md, and enforces that every task which has moved
past "Not started" carries an evidence link.

  python3 scripts/task_tracking.py --generate   # rewrite the index (preserves state)
  python3 scripts/task_tracking.py --check       # verify; non-zero exit on drift

Structural columns (Title/Epoch/Depends) are always refreshed from the backlog,
so they cannot drift. State columns (Status/Owner/Evidence) are preserved from
the existing index; a task not yet in the index is seeded from the Detailed
evidence log's status (if present) or defaults to "Not started".
"""
from __future__ import annotations

import pathlib
import re
import sys

ROOT = pathlib.Path(__file__).resolve().parent.parent
BACKLOG = ROOT / "docs" / "BACKLOG.md"
STATUS = ROOT / "docs" / "IMPLEMENTATION_STATUS.md"

BEGIN = "<!-- BEGIN TASK INDEX (generated by scripts/task_tracking.py) -->"
END = "<!-- END TASK INDEX -->"

DEFAULT_STATUS = "Not started"
DEFAULT_OWNER = "_unassigned_"
DEFAULT_EVIDENCE = "—"
DETAIL_LINK = "[detail](#detailed-evidence-log)"
ALL_STATUSES = {"Not started", "In progress", "Blocked", "In review", "Complete"}
ACTIVE_STATUSES = {"In progress", "In review", "Complete"}
# An evidence cell must actually look like evidence, not merely be non-blank:
# a markdown link, a URL, a commit-ish hex token, or "run <n>".
EVIDENCE_RE = re.compile(r"\[.+?\]\(.+?\)|https?://|\b[0-9a-f]{7,40}\b|\brun \d+", re.I)


def parse_backlog() -> list[tuple[str, str, str, str]]:
    """Return (id, title, epoch, depends) for every backlog task, in order."""
    tasks: list[tuple[str, str, str, str]] = []
    epoch = "—"
    lines = BACKLOG.read_text().splitlines()
    for i, line in enumerate(lines):
        m = re.match(r"^##\s+(E\d+):", line)
        if m:
            epoch = m.group(1)
            continue
        m = re.match(r"^###\s+(WG-\d+):\s*(.+?)\s*$", line)
        if m:
            depends = "—"
            for j in range(i + 1, len(lines)):
                if re.match(r"^#{2,3}\s", lines[j]):  # stop at the next task/epoch heading
                    break
                d = re.match(r"^\*\*Dependencies:\*\*\s*(.+?)\s*$", lines[j])
                if d:
                    depends = d.group(1).strip()
                    break
            tasks.append((m.group(1), m.group(2), epoch, depends))
    return tasks


def _index_text() -> str | None:
    if not STATUS.exists():
        return None
    m = re.search(re.escape(BEGIN) + r"(.*?)" + re.escape(END), STATUS.read_text(), re.S)
    return m.group(1) if m else None


def parse_existing_state() -> dict[str, tuple[str, str, str]]:
    """id -> (status, owner, evidence) from the current generated index block."""
    state: dict[str, tuple[str, str, str]] = {}
    block = _index_text()
    if not block:
        return state
    for row in block.splitlines():
        cells = [c.strip() for c in row.strip().strip("|").split("|")]
        if len(cells) >= 7 and re.fullmatch(r"WG-\d+", cells[0]):
            state[cells[0]] = (cells[4], cells[5], cells[6])
    return state


def seed_from_detailed_log() -> dict[str, str]:
    """id -> status from the Detailed evidence log rows (col 2 is a status word)."""
    seed: dict[str, str] = {}
    if not STATUS.exists():
        return seed
    for row in STATUS.read_text().splitlines():
        m = re.match(
            r"^\|\s*(WG-\d+)\s*\|\s*(Not started|In progress|Blocked|In review|Complete)\s*\|",
            row,
        )
        if m:
            seed[m.group(1)] = m.group(2)
    return seed


def build_index(tasks, state, seed) -> str:
    rows = [
        "| Task | Title | Epoch | Depends | Status | Owner | Evidence |",
        "|---|---|---|---|---|---|---|",
    ]
    for tid, title, epoch, depends in tasks:
        if tid in state:
            status, owner, evidence = state[tid]
        elif tid in seed:
            status = seed[tid]
            owner = DEFAULT_OWNER
            evidence = DETAIL_LINK if status in ACTIVE_STATUSES else DEFAULT_EVIDENCE
        else:
            status, owner, evidence = DEFAULT_STATUS, DEFAULT_OWNER, DEFAULT_EVIDENCE
        title = title.replace("|", r"\|")
        rows.append(f"| {tid} | {title} | {epoch} | {depends} | {status} | {owner} | {evidence} |")
    return "\n".join(rows)


def generate() -> int:
    text = STATUS.read_text() if STATUS.exists() else ""
    if text.count(BEGIN) != 1 or text.count(END) != 1:
        print(
            f"error: {STATUS} must contain exactly one '{BEGIN}' / '{END}' pair.",
            file=sys.stderr,
        )
        return 2
    tasks = parse_backlog()
    block = build_index(tasks, parse_existing_state(), seed_from_detailed_log())
    new = re.sub(
        re.escape(BEGIN) + r".*?" + re.escape(END),
        BEGIN + "\n" + block + "\n" + END,
        text,
        count=1,
        flags=re.S,
    )
    STATUS.write_text(new)
    print(f"Generated task index: {len(tasks)} tasks.")
    return 0


def check() -> int:
    text = STATUS.read_text() if STATUS.exists() else ""
    if text.count(BEGIN) != 1 or text.count(END) != 1:
        return _fail([f"expected exactly one task-index marker pair in {STATUS.name}"])

    tasks = parse_backlog()
    backlog_ids = [t[0] for t in tasks]
    backlog_set = set(backlog_ids)
    state = parse_existing_state()
    errors: list[str] = []

    for tid in backlog_ids:
        if tid not in state:
            errors.append(f"backlog task {tid} is missing from the task index")
    for tid in state:
        if tid not in backlog_set:
            errors.append(f"index row {tid} is not a backlog task (orphan)")
    for tid, (status, _owner, evidence) in state.items():
        if status not in ALL_STATUSES:
            errors.append(f"{tid}: invalid status '{status}'")
        if status in ACTIVE_STATUSES and not EVIDENCE_RE.search(evidence or ""):
            errors.append(f"{tid}: status '{status}' needs a real evidence link (got {evidence!r})")

    # Structural drift: Title/Epoch/Depends must match a fresh generation.
    expected = build_index(tasks, state, seed_from_detailed_log())
    current = _index_text()
    if current is not None and current.strip() != expected.strip():
        errors.append(
            "task index is stale (structural columns differ from the backlog) "
            "— run: python3 scripts/task_tracking.py --generate"
        )

    if errors:
        return _fail(errors)
    print(
        f"Task tracking OK: {len(backlog_ids)} tasks tracked; statuses valid; "
        "evidence present for every active/complete task."
    )
    return 0


def _fail(errors: list[str]) -> int:
    print("TASK TRACKING CHECK FAILED:")
    for e in errors:
        print("  -", e)
    print("\nFix: python3 scripts/task_tracking.py --generate, then fill Status/Evidence.")
    return 1


if __name__ == "__main__":
    mode = sys.argv[1] if len(sys.argv) > 1 else "--check"
    if mode == "--generate":
        sys.exit(generate())
    if mode == "--check":
        sys.exit(check())
    print("usage: task_tracking.py --generate|--check", file=sys.stderr)
    sys.exit(2)
